### ISSUE TITLE
error：onnxruntime-win-x64-gpu-1.14.1 vs17 cuda11.7 编译成功，运行报错

### ISSUE THREAD

**Issue by jun20061588** [NagatoYuki0943/anomalib-onnxruntime-cpp#5]
请教一下你用的是onnxruntime-win-x64-gpu哪个版本？我onnxruntime-win-x64-gpu-1.14.1编译报错
TensorrtExecutionProvider CUDAExecutionProvider CPUExecutionProvider
2023-10-20 15:56:30.2506761 [W:onnxruntime:, session_state.cc:1136 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-10-20 15:56:30.2550638 [W:onnxruntime:, session_state.cc:1138 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
Number of inputs = 1
Number of output = 2
input_dims: -1 3 256 256
output_dims: -1 -1 -1 -1
output_dims: -1

**Comment by NagatoYuki0943** [comment]
这个看样子是动态形状的问题，可以试一试把 https://github.com/NagatoYuki0943/anomalib-onnxruntime-cpp/blob/main/inference.hpp#L138和https://github.com/NagatoYuki0943/anomalib-onnxruntime-cpp/blob/main/inference.hpp#L148 这2行的注释给去掉，然后再加上一行 `this->output_dims[1] = { 1 };` 试一下，目前只能一次推理一张图片

**Comment by jun20061588** [comment]
output_shape_info: 000001782CF3BD70
before input_dims: -1 3 256 256
after input_dims: 1 3 256 256
before output_dims: -1 -1 -1 -1
设置input_dims没问题
设置output_dims的时候this->output_dims[0] = { 1, 1, 256, 256 };会报错vector越界

**Comment by NagatoYuki0943** [comment]
以下3种我测试了都正常，onnxruntime是1.16.1的版本
你看看是不是模型输出个数和以下改的代码不一致造成的

1个输出的模型只加如下一行
```python
this->output_dims[0] = { 1, 1, 256, 256 };
```

patchcore模型加2行
```python
this->output_dims[0] = { 1, 1, 256, 256 }; // single output
this->output_dims[1] = { 1 };              // patchcore add this line
```

efficient_ad模型加3行
```python
this->output_dims[0] = { 1, 1, 256, 256 }; // single output
this->output_dims[1] = { 1, 1, 256, 256 }; // efficient_ad add 2 lines
this->output_dims[2] = { 1, 1, 256, 256 }; // efficient_ad add 2 lines
```

**Comment by jun20061588** [comment]
OK了，非常感谢，开始的时候用的是patchcore模型，后面报错改成padim模型了，然后一直按照this->output_dims[0] = { 1, 1, 256, 256 }; // single output
this->output_dims[1] = { 1 };   改的，现在好了，现在padim模型this->output_dims[0] = { 1, 1, 256, 256 };，也是OK的
